import type { QueryTask } from "../constants";

export const lv1: QueryTask[] = [
	// 客户公司表查询 - 基础统计
	{
		id: "1-1-1",
		text: "统计不同星级客户的数量分布",
		difficulty: 1,
		category: "客户统计",
		description: "按星级分组统计客户数量",
		tables: ["companies"],
	},
	{
		id: "1-1-2",
		text: "找出最近30天创建的新客户",
		difficulty: 1,
		category: "客户统计",
		description: "时间范围过滤查询",
		tables: ["companies"],
	},
	{
		id: "1-1-3",
		text: "统计各个国家的客户数量排名",
		difficulty: 1,
		category: "客户统计",
		description: "地域分布统计",
		tables: ["companies"],
	},
	{
		id: "1-1-4",
		text: "查找名称包含'科技'的所有公司",
		difficulty: 1,
		category: "客户搜索",
		description: "模糊匹配查询",
		tables: ["companies"],
	},
	{
		id: "1-1-5",
		text: "统计私海客户与公海客户的比例",
		difficulty: 1,
		category: "客户统计",
		description: "客户状态分布",
		tables: ["companies"],
	},
	{
		id: "1-1-6",
		text: "找出有官网的客户公司数量",
		difficulty: 1,
		category: "客户统计",
		description: "非空字段统计",
		tables: ["companies"],
	},
	{
		id: "1-1-7",
		text: "查询创建时间最早的10个客户",
		difficulty: 1,
		category: "客户查询",
		description: "排序和限制查询",
		tables: ["companies"],
	},
	{
		id: "1-1-8",
		text: "查询公司所有客户",
		difficulty: 1,
		category: "客户查询",
		description: "查询所有客户",
		tables: ["companies"],
	},
	{
		id: "1-1-9",
		text: "查询客户名称长度超过10个字符的公司",
		difficulty: 1,
		category: "客户筛选",
		description: "字符串长度条件",
		tables: ["companies"],
	},
	{
		id: "1-1-10",
		text: "统计每个月新增的客户数量",
		difficulty: 1,
		category: "客户统计",
		description: "按月分组统计",
		tables: ["companies"],
	},
	{
		id: "1-1-11",
		text: "查找官网域名为'.cn'的中国公司",
		difficulty: 1,
		category: "客户筛选",
		description: "域名后缀匹配",
		tables: ["companies"],
	},
	{
		id: "1-1-12",
		text: "统计今年创建的客户总数",
		difficulty: 1,
		category: "客户统计",
		description: "年度统计查询",
		tables: ["companies"],
	},

	// 联系人表查询 - 基础分析
	{
		id: "1-2-1",
		text: "统计男女联系人的数量分布",
		difficulty: 1,
		category: "联系人统计",
		description: "性别分组统计",
		tables: ["contacts"],
	},
	{
		id: "1-2-2",
		text: "找出职位为'CEO'或'总经理'的联系人",
		difficulty: 1,
		category: "联系人查询",
		description: "条件过滤查询",
		tables: ["contacts"],
	},
	{
		id: "1-2-3",
		text: "统计有WhatsApp号码的联系人比例",
		difficulty: 1,
		category: "联系人统计",
		description: "比例计算",
		tables: ["contacts"],
	},
	{
		id: "1-2-4",
		text: "查找邮箱域名为'.com'的联系人数量",
		difficulty: 1,
		category: "联系人统计",
		description: "模式匹配查询",
		tables: ["contacts"],
	},
	{
		id: "1-2-5",
		text: "统计主联系人与普通联系人的数量",
		difficulty: 1,
		category: "联系人统计",
		description: "标志位分组统计",
		tables: ["contacts"],
	},
	{
		id: "1-2-6",
		text: "找出电话区号为'+86'的中国联系人",
		difficulty: 1,
		category: "联系人查询",
		description: "前缀匹配查询",
		tables: ["contacts"],
	},
	{
		id: "1-2-7",
		text: "查询姓名最长的联系人",
		difficulty: 1,
		category: "联系人查询",
		description: "字符串长度排序",
		tables: ["contacts"],
	},
	{
		id: "1-2-8",
		text: "统计不同职位的联系人数量分布",
		difficulty: 1,
		category: "联系人统计",
		description: "职位分组统计",
		tables: ["contacts"],
	},
	{
		id: "1-2-9",
		text: "找出没有填写电话号码的联系人",
		difficulty: 1,
		category: "联系人查询",
		description: "空值筛选查询",
		tables: ["contacts"],
	},
	{
		id: "1-2-10",
		text: "查询本月新增的联系人数量",
		difficulty: 1,
		category: "联系人统计",
		description: "月度新增统计",
		tables: ["contacts"],
	},
	{
		id: "1-2-11",
		text: "统计邮箱地址包含数字的联系人",
		difficulty: 1,
		category: "联系人统计",
		description: "邮箱格式分析",
		tables: ["contacts"],
	},
	{
		id: "1-2-12",
		text: "查找职位包含'经理'的所有联系人",
		difficulty: 1,
		category: "联系人查询",
		description: "职位模糊匹配",
		tables: ["contacts"],
	},

	// 业务员表查询 - 人员分析
	{
		id: "1-3-1",
		text: "统计各个部门的人员数量",
		difficulty: 1,
		category: "业务员统计",
		description: "部门分组统计",
		tables: ["salesUsers"],
	},
	{
		id: "1-3-2",
		text: "找出昵称最长的业务员",
		difficulty: 1,
		category: "业务员查询",
		description: "字符串长度排序",
		tables: ["salesUsers"],
	},
	{
		id: "1-3-3",
		text: "统计有头像的业务员比例",
		difficulty: 1,
		category: "业务员统计",
		description: "比例计算",
		tables: ["salesUsers"],
	},
	{
		id: "1-3-4",
		text: "查询最近加入的10个业务员",
		difficulty: 1,
		category: "业务员查询",
		description: "时间排序限制",
		tables: ["salesUsers"],
	},
	{
		id: "1-3-5",
		text: "统计每个部门的平均入职时间",
		difficulty: 1,
		category: "业务员统计",
		description: "时间聚合统计",
		tables: ["salesUsers"],
	},
	{
		id: "1-3-6",
		text: "查找用户名包含'admin'的管理员",
		difficulty: 1,
		category: "业务员查询",
		description: "用户名模式匹配",
		tables: ["salesUsers"],
	},
	{
		id: "1-3-7",
		text: "统计工龄超过2年的业务员数量",
		difficulty: 1,
		category: "业务员统计",
		description: "工龄计算统计",
		tables: ["salesUsers"],
	},
	{
		id: "1-3-8",
		text: "查询所有部门的名称列表",
		difficulty: 1,
		category: "业务员查询",
		description: "去重查询",
		tables: ["salesUsers"],
	},
	{
		id: "1-3-9",
		text: "找出昵称为空的业务员",
		difficulty: 1,
		category: "业务员查询",
		description: "空值查询",
		tables: ["salesUsers"],
	},
	{
		id: "1-3-10",
		text: "统计今年新加入的业务员数量",
		difficulty: 1,
		category: "业务员统计",
		description: "年度新增统计",
		tables: ["salesUsers"],
	},

	// 跟进动态表查询 - 活动分析
	{
		id: "1-4-1",
		text: "统计每月的跟进记录数量趋势",
		difficulty: 1,
		category: "跟进统计",
		description: "时间分组统计",
		tables: ["followUps"],
	},
	{
		id: "1-4-2",
		text: "找出跟进内容最长的记录",
		difficulty: 1,
		category: "跟进查询",
		description: "内容长度排序",
		tables: ["followUps"],
	},
	{
		id: "1-4-3",
		text: "统计不同跟进类型的使用频率",
		difficulty: 1,
		category: "跟进统计",
		description: "类型分组统计",
		tables: ["followUps"],
	},
	{
		id: "1-4-4",
		text: "查询最近一周的跟进活动统计",
		difficulty: 1,
		category: "跟进统计",
		description: "时间范围统计",
		tables: ["followUps"],
	},
	{
		id: "1-4-5",
		text: "统计每天的跟进活动数量",
		difficulty: 1,
		category: "跟进统计",
		description: "日度活动统计",
		tables: ["followUps"],
	},
	{
		id: "1-4-6",
		text: "查找跟进内容包含'电话'的记录",
		difficulty: 1,
		category: "跟进查询",
		description: "内容关键词搜索",
		tables: ["followUps"],
	},
	{
		id: "1-4-7",
		text: "统计工作日vs周末的跟进活动比例",
		difficulty: 1,
		category: "跟进分析",
		description: "工作时间分析",
		tables: ["followUps"],
	},
	{
		id: "1-4-8",
		text: "查询跟进记录总数",
		difficulty: 1,
		category: "跟进统计",
		description: "基础计数查询",
		tables: ["followUps"],
	},
	{
		id: "1-4-9",
		text: "找出今日的跟进活动",
		difficulty: 1,
		category: "跟进查询",
		description: "当日活动查询",
		tables: ["followUps"],
	},
	{
		id: "1-4-10",
		text: "统计跟进内容平均长度",
		difficulty: 1,
		category: "跟进统计",
		description: "内容长度平均值",
		tables: ["followUps"],
	},

	// 商机表查询 - 销售分析
	{
		id: "1-5-1",
		text: "统计不同阶段商机的数量和总金额",
		difficulty: 1,
		category: "商机统计",
		description: "阶段分组统计",
		tables: ["opportunities"],
	},
	{
		id: "1-5-2",
		text: "找出金额超过10万美元的大商机",
		difficulty: 1,
		category: "商机查询",
		description: "金额条件过滤",
		tables: ["opportunities"],
	},
	{
		id: "1-5-3",
		text: "统计不同币种的商机分布",
		difficulty: 1,
		category: "商机统计",
		description: "币种分组统计",
		tables: ["opportunities"],
	},
	{
		id: "1-5-4",
		text: "查询平均商机周期(创建到下单的时间)",
		difficulty: 1,
		category: "商机分析",
		description: "时间差计算",
		tables: ["opportunities"],
	},
	{
		id: "1-5-5",
		text: "找出本季度新增的商机数量",
		difficulty: 1,
		category: "商机统计",
		description: "季度时间范围",
		tables: ["opportunities"],
	},
	{
		id: "1-5-6",
		text: "统计商机的平均金额",
		difficulty: 1,
		category: "商机统计",
		description: "金额平均值计算",
		tables: ["opportunities"],
	},
	{
		id: "1-5-7",
		text: "查找金额最高的单个商机",
		difficulty: 1,
		category: "商机查询",
		description: "最大值查询",
		tables: ["opportunities"],
	},
	{
		id: "1-5-8",
		text: "统计已成交商机的总金额",
		difficulty: 1,
		category: "商机统计",
		description: "成交金额统计",
		tables: ["opportunities"],
	},
	{
		id: "1-5-9",
		text: "查询商机名称包含'系统'的项目",
		difficulty: 1,
		category: "商机查询",
		description: "项目类型筛选",
		tables: ["opportunities"],
	},
	{
		id: "1-5-10",
		text: "统计商机预计成交时间分布",
		difficulty: 1,
		category: "商机分析",
		description: "时间分布统计",
		tables: ["opportunities"],
	},

	// WhatsApp消息表查询 - 沟通分析
	{
		id: "1-6-1",
		text: "统计发送和接收消息的比例",
		difficulty: 1,
		category: "消息统计",
		description: "方向分组统计",
		tables: ["whatsappMessages"],
	},
	{
		id: "1-6-2",
		text: "找出消息内容最长的对话记录",
		difficulty: 1,
		category: "消息查询",
		description: "内容长度排序",
		tables: ["whatsappMessages"],
	},
	{
		id: "1-6-3",
		text: "统计包含媒体文件的消息比例",
		difficulty: 1,
		category: "消息统计",
		description: "媒体标志统计",
		tables: ["whatsappMessages"],
	},
	{
		id: "1-6-4",
		text: "查询每日消息量的变化趋势",
		difficulty: 1,
		category: "消息分析",
		description: "日期分组趋势",
		tables: ["whatsappMessages"],
	},
	{
		id: "1-6-5",
		text: "找出最活跃的聊天时间段",
		difficulty: 1,
		category: "消息分析",
		description: "时间段统计",
		tables: ["whatsappMessages"],
	},
	{
		id: "1-6-6",
		text: "统计消息总数",
		difficulty: 1,
		category: "消息统计",
		description: "基础计数统计",
		tables: ["whatsappMessages"],
	},
	{
		id: "1-6-7",
		text: "查询今日发送的消息数量",
		difficulty: 1,
		category: "消息统计",
		description: "当日发送统计",
		tables: ["whatsappMessages"],
	},
	{
		id: "1-6-8",
		text: "统计消息平均长度",
		difficulty: 1,
		category: "消息分析",
		description: "内容长度平均值",
		tables: ["whatsappMessages"],
	},
	{
		id: "1-6-9",
		text: "查找包含表情符号的消息",
		difficulty: 1,
		category: "消息查询",
		description: "表情符号检测",
		tables: ["whatsappMessages"],
	},
	{
		id: "1-6-10",
		text: "统计不同消息类型的分布",
		difficulty: 1,
		category: "消息统计",
		description: "消息类型分组",
		tables: ["whatsappMessages"],
	},

	// 客户-业务员关系表查询 - 关系管理
	{
		id: "1-7-1",
		text: "统计主负责人与协作者的关系分布",
		difficulty: 1,
		category: "关系统计",
		description: "关系类型分组",
		tables: ["companyUserRelations"],
	},
	{
		id: "1-7-2",
		text: "找出管理客户最多的业务员",
		difficulty: 1,
		category: "关系查询",
		description: "计数排序查询",
		tables: ["companyUserRelations"],
	},
	{
		id: "1-7-3",
		text: "统计平均每个客户有几个负责人",
		difficulty: 1,
		category: "关系统计",
		description: "平均值计算",
		tables: ["companyUserRelations"],
	},
	{
		id: "1-7-4",
		text: "查询关系建立的总数",
		difficulty: 1,
		category: "关系统计",
		description: "基础计数查询",
		tables: ["companyUserRelations"],
	},
	{
		id: "1-7-5",
		text: "统计今年新建立的客户关系数量",
		difficulty: 1,
		category: "关系统计",
		description: "年度新增关系",
		tables: ["companyUserRelations"],
	},
	{
		id: "1-7-6",
		text: "查找只有一个负责人的客户关系",
		difficulty: 1,
		category: "关系查询",
		description: "单一负责人筛选",
		tables: ["companyUserRelations"],
	},
	{
		id: "1-7-7",
		text: "统计本月新增的客户关系",
		difficulty: 1,
		category: "关系统计",
		description: "月度关系增长",
		tables: ["companyUserRelations"],
	},
];
