import type { QueryTask } from "../constants";

export const lv2: QueryTask[] = [
	// 公司-联系人关系 (companies + contacts)
	{
		id: "2-1-1",
		text: "找出没有联系人的公司",
		difficulty: 2,
		category: "数据完整性",
		description: "LEFT JOIN查找空值",
		tables: ["companies", "contacts"],
	},
	{
		id: "2-1-2",
		text: "统计每个公司的联系人数量",
		difficulty: 2,
		category: "关联统计",
		description: "JOIN后分组计数",
		tables: ["companies", "contacts"],
	},
	{
		id: "2-1-3",
		text: "找出联系人最多的前10个公司",
		difficulty: 2,
		category: "关联排序",
		description: "JOIN分组排序限制",
		tables: ["companies", "contacts"],
	},
	{
		id: "2-1-4",
		text: "查询只有一个联系人的公司数量",
		difficulty: 2,
		category: "关联统计",
		description: "HAVING条件过滤",
		tables: ["companies", "contacts"],
	},
	{
		id: "2-1-5",
		text: "找出有女性CEO的公司列表",
		difficulty: 2,
		category: "高管分析",
		description: "职位性别关联查询",
		tables: ["companies", "contacts"],
	},
	{
		id: "2-1-6",
		text: "统计各国公司的联系人总数",
		difficulty: 2,
		category: "地域分析",
		description: "按国家聚合统计",
		tables: ["companies", "contacts"],
	},
	{
		id: "2-1-7",
		text: "查询有多个主联系人的公司",
		difficulty: 2,
		category: "数据质量",
		description: "主联系人重复检查",
		tables: ["companies", "contacts"],
	},
	{
		id: "2-1-8",
		text: "找出联系人邮箱域名与公司官网匹配的记录",
		difficulty: 2,
		category: "数据一致性",
		description: "域名匹配验证",
		tables: ["companies", "contacts"],
	},

	// 公司-业务员关系 (companies + salesUsers/companyUserRelations)
	{
		id: "2-2-1",
		text: "找出每个业务员负责的客户数量",
		difficulty: 2,
		category: "业绩统计",
		description: "关系表JOIN统计",
		tables: ["companies", "companyUserRelations"],
	},
	{
		id: "2-2-2",
		text: "查询没有业务员负责的客户",
		difficulty: 2,
		category: "数据完整性",
		description: "LEFT JOIN查找孤立数据",
		tables: ["companies", "companyUserRelations"],
	},
	{
		id: "2-2-3",
		text: "统计每个部门管理的客户数量",
		difficulty: 2,
		category: "部门统计",
		description: "三层关联统计",
		tables: ["companies", "salesUsers"],
	},
	{
		id: "2-2-4",
		text: "找出客户星级最高的业务员",
		difficulty: 2,
		category: "业绩分析",
		description: "关联后聚合排序",
		tables: ["companies", "salesUsers"],
	},
	{
		id: "2-2-5",
		text: "查询管理超过10个客户的业务员",
		difficulty: 2,
		category: "工作量分析",
		description: "客户数量阈值筛选",
		tables: ["companies", "companyUserRelations"],
	},
	{
		id: "2-2-6",
		text: "统计各部门管理的五星级客户数量",
		difficulty: 2,
		category: "优质客户分析",
		description: "部门星级客户统计",
		tables: ["companies", "salesUsers"],
	},
	{
		id: "2-2-7",
		text: "找出负责海外客户最多的业务员",
		difficulty: 2,
		category: "海外业务",
		description: "地域业务分析",
		tables: ["companies", "salesUsers"],
	},
	{
		id: "2-2-8",
		text: "查询业务员与客户的配对关系建立时间",
		difficulty: 2,
		category: "关系建立",
		description: "关系时间分析",
		tables: ["companies", "companyUserRelations"],
	},

	// 公司-跟进记录关系 (companies + followUps)
	{
		id: "2-3-1",
		text: "找出从未被跟进的客户",
		difficulty: 2,
		category: "跟进分析",
		description: "LEFT JOIN查找未跟进",
		tables: ["companies", "followUps"],
	},
	{
		id: "2-3-2",
		text: "统计每个客户的跟进频率",
		difficulty: 2,
		category: "跟进统计",
		description: "时间间隔计算",
		tables: ["companies", "followUps"],
	},
	{
		id: "2-3-3",
		text: "查询最近跟进的客户列表",
		difficulty: 2,
		category: "跟进查询",
		description: "时间排序关联",
		tables: ["companies", "followUps"],
	},
	{
		id: "2-3-4",
		text: "找出跟进次数最多的客户",
		difficulty: 2,
		category: "跟进排序",
		description: "计数排序查询",
		tables: ["companies", "followUps"],
	},
	{
		id: "2-3-5",
		text: "统计不同星级客户的平均跟进频率",
		difficulty: 2,
		category: "跟进策略",
		description: "星级跟进模式分析",
		tables: ["companies", "followUps"],
	},
	{
		id: "2-3-6",
		text: "查询超过30天未跟进的重要客户",
		difficulty: 2,
		category: "客户维护",
		description: "跟进滞后预警",
		tables: ["companies", "followUps"],
	},
	{
		id: "2-3-7",
		text: "找出跟进内容最丰富的客户",
		difficulty: 2,
		category: "跟进质量",
		description: "跟进内容长度分析",
		tables: ["companies", "followUps"],
	},

	// 公司-商机关系 (companies + opportunities)
	{
		id: "2-4-1",
		text: "找出没有商机的客户公司",
		difficulty: 2,
		category: "商机分析",
		description: "LEFT JOIN查找空值",
		tables: ["companies", "opportunities"],
	},
	{
		id: "2-4-2",
		text: "统计每个客户的商机总价值",
		difficulty: 2,
		category: "价值分析",
		description: "金额求和统计",
		tables: ["companies", "opportunities"],
	},
	{
		id: "2-4-3",
		text: "查询商机价值最高的客户",
		difficulty: 2,
		category: "价值排序",
		description: "聚合后排序",
		tables: ["companies", "opportunities"],
	},
	{
		id: "2-4-4",
		text: "找出商机数量最多的客户",
		difficulty: 2,
		category: "商机统计",
		description: "计数排序查询",
		tables: ["companies", "opportunities"],
	},
	{
		id: "2-4-5",
		text: "统计不同国家客户的商机转化率",
		difficulty: 2,
		category: "地域转化",
		description: "按地域分析转化率",
		tables: ["companies", "opportunities"],
	},
	{
		id: "2-4-6",
		text: "查询五星级客户的平均商机价值",
		difficulty: 2,
		category: "优质客户价值",
		description: "星级客户商机分析",
		tables: ["companies", "opportunities"],
	},
	{
		id: "2-4-7",
		text: "找出商机周期最长的客户类型",
		difficulty: 2,
		category: "销售周期",
		description: "客户类型销售周期",
		tables: ["companies", "opportunities"],
	},

	// 联系人-WhatsApp消息关系 (contacts + whatsappMessages)
	{
		id: "2-5-1",
		text: "找出有WhatsApp聊天记录的联系人",
		difficulty: 2,
		category: "沟通分析",
		description: "关联查找活跃联系人",
		tables: ["contacts", "whatsappMessages"],
	},
	{
		id: "2-5-2",
		text: "统计每个联系人的消息数量",
		difficulty: 2,
		category: "沟通统计",
		description: "消息计数统计",
		tables: ["contacts", "whatsappMessages"],
	},
	{
		id: "2-5-3",
		text: "查询最活跃的WhatsApp联系人",
		difficulty: 2,
		category: "活跃度分析",
		description: "消息频率排序",
		tables: ["contacts", "whatsappMessages"],
	},
	{
		id: "2-5-4",
		text: "找出最近收到消息的联系人",
		difficulty: 2,
		category: "最新活动",
		description: "时间排序关联",
		tables: ["contacts", "whatsappMessages"],
	},
	{
		id: "2-5-5",
		text: "统计男女联系人的WhatsApp使用率",
		difficulty: 2,
		category: "性别沟通偏好",
		description: "性别与沟通方式",
		tables: ["contacts", "whatsappMessages"],
	},
	{
		id: "2-5-6",
		text: "查询CEO级别联系人的消息特征",
		difficulty: 2,
		category: "高管沟通",
		description: "职位与沟通模式",
		tables: ["contacts", "whatsappMessages"],
	},
	{
		id: "2-5-7",
		text: "找出从不主动发消息的联系人",
		difficulty: 2,
		category: "沟通模式",
		description: "被动沟通者识别",
		tables: ["contacts", "whatsappMessages"],
	},

	// 业务员-跟进记录关系 (salesUsers + followUps)
	{
		id: "2-6-1",
		text: "统计每个业务员的跟进活跃度",
		difficulty: 2,
		category: "业务员绩效",
		description: "跟进频率统计",
		tables: ["salesUsers", "followUps"],
	},
	{
		id: "2-6-2",
		text: "找出跟进最频繁的业务员",
		difficulty: 2,
		category: "绩效排序",
		description: "活跃度排序查询",
		tables: ["salesUsers", "followUps"],
	},
	{
		id: "2-6-3",
		text: "查询各部门的跟进工作量",
		difficulty: 2,
		category: "部门绩效",
		description: "部门级别统计",
		tables: ["salesUsers", "followUps"],
	},
	{
		id: "2-6-4",
		text: "找出本月跟进次数最多的业务员",
		difficulty: 2,
		category: "月度绩效",
		description: "时间范围排序",
		tables: ["salesUsers", "followUps"],
	},
	{
		id: "2-6-5",
		text: "统计业务员的平均跟进内容长度",
		difficulty: 2,
		category: "跟进质量",
		description: "跟进详细程度分析",
		tables: ["salesUsers", "followUps"],
	},
	{
		id: "2-6-6",
		text: "查询周末仍在跟进的敬业业务员",
		difficulty: 2,
		category: "工作态度",
		description: "工作时间分析",
		tables: ["salesUsers", "followUps"],
	},

	// 业务员-商机关系 (salesUsers + opportunities)
	{
		id: "2-7-1",
		text: "统计每个业务员的商机业绩",
		difficulty: 2,
		category: "销售业绩",
		description: "商机金额统计",
		tables: ["salesUsers", "opportunities"],
	},
	{
		id: "2-7-2",
		text: "找出成交金额最高的业务员",
		difficulty: 2,
		category: "业绩排序",
		description: "金额排序查询",
		tables: ["salesUsers", "opportunities"],
	},
	{
		id: "2-7-3",
		text: "查询各部门的商机总价值",
		difficulty: 2,
		category: "部门业绩",
		description: "部门金额统计",
		tables: ["salesUsers", "opportunities"],
	},
	{
		id: "2-7-4",
		text: "找出商机成功率最高的业务员",
		difficulty: 2,
		category: "成功率分析",
		description: "转化率计算",
		tables: ["salesUsers", "opportunities"],
	},
	{
		id: "2-7-5",
		text: "统计新员工vs老员工的商机表现",
		difficulty: 2,
		category: "经验对比",
		description: "工龄与业绩关系",
		tables: ["salesUsers", "opportunities"],
	},
	{
		id: "2-7-6",
		text: "查询商机金额超过部门平均值的业务员",
		difficulty: 2,
		category: "超额业绩",
		description: "部门内业绩对比",
		tables: ["salesUsers", "opportunities"],
	},

	// 联系人-跟进记录关系 (contacts + followUps)
	{
		id: "2-8-1",
		text: "统计每个联系人被跟进的频率",
		difficulty: 2,
		category: "联系人关注度",
		description: "个人跟进统计",
		tables: ["contacts", "followUps"],
	},
	{
		id: "2-8-2",
		text: "找出最受关注的联系人",
		difficulty: 2,
		category: "关注度排序",
		description: "跟进次数排序",
		tables: ["contacts", "followUps"],
	},
	{
		id: "2-8-3",
		text: "查询CEO级别联系人的跟进情况",
		difficulty: 2,
		category: "高管跟进",
		description: "重要联系人维护",
		tables: ["contacts", "followUps"],
	},
	{
		id: "2-8-4",
		text: "统计男女联系人的跟进差异",
		difficulty: 2,
		category: "性别差异分析",
		description: "性别与跟进模式",
		tables: ["contacts", "followUps"],
	},

	// 联系人-商机关系 (contacts + opportunities)
	{
		id: "2-9-1",
		text: "找出关联商机最多的联系人",
		difficulty: 2,
		category: "商机关联",
		description: "联系人商机数量",
		tables: ["contacts", "opportunities"],
	},
	{
		id: "2-9-2",
		text: "统计不同职位联系人的商机价值",
		difficulty: 2,
		category: "职位价值分析",
		description: "职位与商机关系",
		tables: ["contacts", "opportunities"],
	},
	{
		id: "2-9-3",
		text: "查询主联系人vs普通联系人的商机差异",
		difficulty: 2,
		category: "联系人重要性",
		description: "联系人等级与商机",
		tables: ["contacts", "opportunities"],
	},

	// 跟进记录-商机关系 (followUps + opportunities)
	{
		id: "2-10-1",
		text: "分析跟进活动对商机推进的影响",
		difficulty: 2,
		category: "跟进效果",
		description: "跟进与商机阶段",
		tables: ["followUps", "opportunities"],
	},
	{
		id: "2-10-2",
		text: "统计高价值商机的跟进密度",
		difficulty: 2,
		category: "重点商机维护",
		description: "商机价值与跟进",
		tables: ["followUps", "opportunities"],
	},
	{
		id: "2-10-3",
		text: "查询跟进活动最密集的商机阶段",
		difficulty: 2,
		category: "销售阶段分析",
		description: "阶段跟进特征",
		tables: ["followUps", "opportunities"],
	},

	// 商机-WhatsApp消息关系 (opportunities + whatsappMessages)
	{
		id: "2-11-1",
		text: "分析WhatsApp沟通对商机成交的影响",
		difficulty: 2,
		category: "沟通方式效果",
		description: "沟通渠道与成交",
		tables: ["opportunities", "whatsappMessages"],
	},
	{
		id: "2-11-2",
		text: "统计不同商机阶段的WhatsApp活跃度",
		difficulty: 2,
		category: "阶段沟通特征",
		description: "销售阶段沟通模式",
		tables: ["opportunities", "whatsappMessages"],
	},

	// 业务员-WhatsApp消息关系 (salesUsers + whatsappMessages)
	{
		id: "2-12-1",
		text: "统计业务员的WhatsApp沟通活跃度",
		difficulty: 2,
		category: "沟通工具使用",
		description: "业务员沟通偏好",
		tables: ["salesUsers", "whatsappMessages"],
	},
	{
		id: "2-12-2",
		text: "查询WhatsApp使用最频繁的部门",
		difficulty: 2,
		category: "部门沟通习惯",
		description: "部门沟通方式分析",
		tables: ["salesUsers", "whatsappMessages"],
	},

	// 业务员关系-其他表组合 (companyUserRelations + 其他表)
	{
		id: "2-13-1",
		text: "分析客户关系建立与跟进活动的时间关联",
		difficulty: 2,
		category: "关系建立效果",
		description: "关系与跟进时机",
		tables: ["companyUserRelations", "followUps"],
	},
	{
		id: "2-13-2",
		text: "统计不同关系类型的商机产出",
		difficulty: 2,
		category: "关系价值分析",
		description: "关系类型与商机",
		tables: ["companyUserRelations", "opportunities"],
	},
	{
		id: "2-13-3",
		text: "查询客户关系与联系人数量的相关性",
		difficulty: 2,
		category: "关系网络分析",
		description: "关系复杂度分析",
		tables: ["companyUserRelations", "contacts"],
	},
];
