import type { QueryTask } from "../constants";

export const lv5: QueryTask[] = [
	// 公司-联系人-业务员-跟进-商机 (核心价值链)
	{
		id: "5-1-1",
		text: "构建完整的客户价值链分析模型",
		difficulty: 5,
		category: "价值链分析",
		description: "全链路价值建模",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
		],
	},
	{
		id: "5-1-2",
		text: "找出最佳的客户管理组合模式",
		difficulty: 5,
		category: "管理模式",
		description: "最优管理组合",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
		],
	},
	{
		id: "5-1-3",
		text: "分析客户全生命周期的价值创造路径",
		difficulty: 5,
		category: "生命周期价值",
		description: "客户价值创造全景",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
		],
	},
	{
		id: "5-1-4",
		text: "构建业务员-联系人-商机的最优匹配矩阵",
		difficulty: 5,
		category: "匹配优化",
		description: "三要素匹配矩阵",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
		],
	},
	{
		id: "5-1-5",
		text: "分析跟进策略对不同类型客户-联系人-商机组合的差异化效果",
		difficulty: 5,
		category: "差异化策略",
		description: "策略效果差异分析",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
		],
	},
	{
		id: "5-1-6",
		text: "找出高价值客户的联系人网络与商机开发最佳实践",
		difficulty: 5,
		category: "高价值实践",
		description: "高价值客户开发模式",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
		],
	},

	// 公司-业务员-跟进-商机-WhatsApp (多渠道商机)
	{
		id: "5-2-1",
		text: "分析多渠道客户管理的综合效果",
		difficulty: 5,
		category: "多渠道分析",
		description: "全渠道效果评估",
		tables: [
			"companies",
			"salesUsers",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "5-2-2",
		text: "找出全渠道客户服务最佳实践",
		difficulty: 5,
		category: "最佳实践",
		description: "服务模式优化",
		tables: [
			"companies",
			"salesUsers",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "5-2-3",
		text: "构建业务员多渠道沟通能力与商机转化的关联模型",
		difficulty: 5,
		category: "能力模型",
		description: "多渠道能力建模",
		tables: [
			"companies",
			"salesUsers",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "5-2-4",
		text: "分析不同国家客户的多渠道商机开发最优策略",
		difficulty: 5,
		category: "地域策略",
		description: "跨国多渠道策略",
		tables: [
			"companies",
			"salesUsers",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "5-2-5",
		text: "找出私海客户多渠道管理的成功模式和关键业务员",
		difficulty: 5,
		category: "私海成功模式",
		description: "私海多渠道管理",
		tables: [
			"companies",
			"salesUsers",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 联系人-业务员-跟进-商机-WhatsApp (联系人价值)
	{
		id: "5-3-1",
		text: "分析联系人管理的全方位效果评估",
		difficulty: 5,
		category: "效果评估",
		description: "联系人价值全景",
		tables: [
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "5-3-2",
		text: "找出最有效的联系人培养路径",
		difficulty: 5,
		category: "培养路径",
		description: "联系人成长轨迹",
		tables: [
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "5-3-3",
		text: "构建联系人响应度与商机成功率的预测模型",
		difficulty: 5,
		category: "预测模型",
		description: "响应度商机预测",
		tables: [
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "5-3-4",
		text: "分析不同职位联系人的多渠道参与对商机价值的贡献",
		difficulty: 5,
		category: "职位价值贡献",
		description: "职位多渠道价值分析",
		tables: [
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "5-3-5",
		text: "找出最能通过多渠道促成大额商机的联系人特征和培养方式",
		difficulty: 5,
		category: "大额商机联系人",
		description: "高价值联系人培养",
		tables: [
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 公司-联系人-业务员-商机-WhatsApp (商机开发全景)
	{
		id: "5-4-1",
		text: "构建客户商机开发的完整视图",
		difficulty: 5,
		category: "开发视图",
		description: "商机全景分析",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "5-4-2",
		text: "找出商机成功率最高的管理模式",
		difficulty: 5,
		category: "成功模式",
		description: "高成功率模式",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "5-4-3",
		text: "分析业务员与客户联系人的WhatsApp互动对商机推进的精准影响",
		difficulty: 5,
		category: "精准影响分析",
		description: "WhatsApp商机推进分析",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "5-4-4",
		text: "构建不同客户类型的最优联系人-业务员-WhatsApp配置方案",
		difficulty: 5,
		category: "配置方案",
		description: "客户类型配置优化",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "5-4-5",
		text: "找出通过WhatsApp快速建立信任并转化商机的成功模式",
		difficulty: 5,
		category: "信任转化模式",
		description: "WhatsApp信任建立模式",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 公司-联系人-跟进-商机-WhatsApp (客户互动质量)
	{
		id: "5-5-1",
		text: "分析客户互动质量对商机的综合影响",
		difficulty: 5,
		category: "互动质量",
		description: "互动与商机关系",
		tables: [
			"companies",
			"contacts",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "5-5-2",
		text: "找出客户满意度最高的服务组合",
		difficulty: 5,
		category: "满意度优化",
		description: "最优服务组合",
		tables: [
			"companies",
			"contacts",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "5-5-3",
		text: "构建多渠道客户互动的质量评估体系",
		difficulty: 5,
		category: "质量评估体系",
		description: "互动质量建模",
		tables: [
			"companies",
			"contacts",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "5-5-4",
		text: "分析客户参与度变化对商机生命周期的预测价值",
		difficulty: 5,
		category: "参与度预测",
		description: "参与度商机预测",
		tables: [
			"companies",
			"contacts",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "5-5-5",
		text: "找出最能提升客户忠诚度和商机价值的互动策略",
		difficulty: 5,
		category: "忠诚度策略",
		description: "忠诚度价值提升",
		tables: [
			"companies",
			"contacts",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 公司-联系人-业务员-跟进-WhatsApp (全渠道客户体验)
	{
		id: "5-6-1",
		text: "构建全渠道客户体验的完整分析框架",
		difficulty: 5,
		category: "客户体验框架",
		description: "全渠道体验建模",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"followUps",
			"whatsappMessages",
		],
	},
	{
		id: "5-6-2",
		text: "分析业务员多渠道服务能力对客户满意度的综合影响",
		difficulty: 5,
		category: "服务能力影响",
		description: "多渠道服务满意度",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"followUps",
			"whatsappMessages",
		],
	},
	{
		id: "5-6-3",
		text: "找出最佳的客户旅程设计和业务员配置方案",
		difficulty: 5,
		category: "客户旅程设计",
		description: "旅程配置优化",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"followUps",
			"whatsappMessages",
		],
	},
	{
		id: "5-6-4",
		text: "分析不同时区客户的全渠道服务最优时间配置",
		difficulty: 5,
		category: "时区服务配置",
		description: "跨时区服务优化",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"followUps",
			"whatsappMessages",
		],
	},

	// 公司-关系表-业务员-跟进-商机 (团队协作商机)
	{
		id: "5-7-1",
		text: "分析团队协作模式对客户商机开发的综合效果",
		difficulty: 5,
		category: "团队协作效果",
		description: "协作商机开发分析",
		tables: [
			"companies",
			"companyUserRelations",
			"salesUsers",
			"followUps",
			"opportunities",
		],
	},
	{
		id: "5-7-2",
		text: "构建最优的客户团队配置与商机分配策略",
		difficulty: 5,
		category: "团队配置策略",
		description: "团队商机配置优化",
		tables: [
			"companies",
			"companyUserRelations",
			"salesUsers",
			"followUps",
			"opportunities",
		],
	},
	{
		id: "5-7-3",
		text: "找出主负责人与协作者的最佳分工模式",
		difficulty: 5,
		category: "分工模式",
		description: "最佳团队分工",
		tables: [
			"companies",
			"companyUserRelations",
			"salesUsers",
			"followUps",
			"opportunities",
		],
	},
	{
		id: "5-7-4",
		text: "分析团队规模对不同价值客户管理效果的影响",
		difficulty: 5,
		category: "团队规模效应",
		description: "规模效应分析",
		tables: [
			"companies",
			"companyUserRelations",
			"salesUsers",
			"followUps",
			"opportunities",
		],
	},

	// 公司-联系人-关系表-业务员-商机 (关系网络商机)
	{
		id: "5-8-1",
		text: "构建客户关系网络对商机开发的影响模型",
		difficulty: 5,
		category: "关系网络模型",
		description: "关系网络商机建模",
		tables: [
			"companies",
			"contacts",
			"companyUserRelations",
			"salesUsers",
			"opportunities",
		],
	},
	{
		id: "5-8-2",
		text: "分析业务员团队与客户联系人网络的最优匹配策略",
		difficulty: 5,
		category: "网络匹配策略",
		description: "团队联系人网络匹配",
		tables: [
			"companies",
			"contacts",
			"companyUserRelations",
			"salesUsers",
			"opportunities",
		],
	},
	{
		id: "5-8-3",
		text: "找出最能发挥协同效应的客户-联系人-团队组合",
		difficulty: 5,
		category: "协同效应组合",
		description: "最优协同组合",
		tables: [
			"companies",
			"contacts",
			"companyUserRelations",
			"salesUsers",
			"opportunities",
		],
	},

	// 联系人-关系表-业务员-跟进-商机 (联系人团队协作)
	{
		id: "5-9-1",
		text: "分析联系人与业务员团队的协作效果对商机的影响",
		difficulty: 5,
		category: "联系人团队协作",
		description: "联系人团队商机分析",
		tables: [
			"contacts",
			"companyUserRelations",
			"salesUsers",
			"followUps",
			"opportunities",
		],
	},
	{
		id: "5-9-2",
		text: "构建联系人参与度与团队跟进强度的最优配比模型",
		difficulty: 5,
		category: "参与度配比",
		description: "联系人团队配比优化",
		tables: [
			"contacts",
			"companyUserRelations",
			"salesUsers",
			"followUps",
			"opportunities",
		],
	},
	{
		id: "5-9-3",
		text: "找出最能激发联系人积极性的团队服务模式",
		difficulty: 5,
		category: "激发积极性",
		description: "联系人积极性提升",
		tables: [
			"contacts",
			"companyUserRelations",
			"salesUsers",
			"followUps",
			"opportunities",
		],
	},

	// 公司-关系表-业务员-商机-WhatsApp (团队多渠道)
	{
		id: "5-10-1",
		text: "分析团队多渠道客户管理的综合绩效",
		difficulty: 5,
		category: "团队多渠道绩效",
		description: "团队多渠道管理分析",
		tables: [
			"companies",
			"companyUserRelations",
			"salesUsers",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "5-10-2",
		text: "构建团队WhatsApp沟通分工与商机转化的最优策略",
		difficulty: 5,
		category: "WhatsApp团队策略",
		description: "团队WhatsApp分工优化",
		tables: [
			"companies",
			"companyUserRelations",
			"salesUsers",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "5-10-3",
		text: "找出团队协作在WhatsApp商机开发中的最佳实践",
		difficulty: 5,
		category: "WhatsApp协作实践",
		description: "WhatsApp团队协作模式",
		tables: [
			"companies",
			"companyUserRelations",
			"salesUsers",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 联系人-关系表-业务员-商机-WhatsApp (联系人团队多渠道)
	{
		id: "5-11-1",
		text: "分析联系人网络与业务员团队的多渠道协作效果",
		difficulty: 5,
		category: "网络多渠道协作",
		description: "联系人团队多渠道分析",
		tables: [
			"contacts",
			"companyUserRelations",
			"salesUsers",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "5-11-2",
		text: "构建联系人WhatsApp活跃度与团队商机开发的关联模型",
		difficulty: 5,
		category: "活跃度团队模型",
		description: "联系人活跃度团队建模",
		tables: [
			"contacts",
			"companyUserRelations",
			"salesUsers",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 公司-关系表-业务员-跟进-WhatsApp (团队全渠道服务)
	{
		id: "5-12-1",
		text: "分析团队全渠道客户服务的协调效果",
		difficulty: 5,
		category: "团队全渠道协调",
		description: "团队服务协调分析",
		tables: [
			"companies",
			"companyUserRelations",
			"salesUsers",
			"followUps",
			"whatsappMessages",
		],
	},
	{
		id: "5-12-2",
		text: "构建团队多渠道服务质量的评估体系",
		difficulty: 5,
		category: "团队服务质量",
		description: "团队多渠道质量评估",
		tables: [
			"companies",
			"companyUserRelations",
			"salesUsers",
			"followUps",
			"whatsappMessages",
		],
	},
];
