import type { QueryTask } from "../constants";

export const lv6: QueryTask[] = [
	// 所有表除WhatsApp (传统CRM分析)
	{
		id: "6-1-1",
		text: "构建客户360度全景视图分析",
		difficulty: 6,
		category: "全景分析",
		description: "客户完整画像",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-1-2",
		text: "找出客户价值最大化的服务模式",
		difficulty: 6,
		category: "价值最大化",
		description: "最优服务策略",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-1-3",
		text: "构建多渠道客户旅程的完整生命周期分析",
		difficulty: 6,
		category: "生命周期分析",
		description: "客户完整旅程建模",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-1-4",
		text: "分析客户忠诚度与多维度业务表现的关联模型",
		difficulty: 6,
		category: "忠诚度模型",
		description: "忠诚度业务关联分析",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 缺少WhatsApp的分析 (传统CRM管理)
	{
		id: "6-2-1",
		text: "分析传统CRM管理模式的效果评估",
		difficulty: 6,
		category: "传统模式",
		description: "非数字化渠道分析",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
		],
	},
	{
		id: "6-2-2",
		text: "找出线下客户管理的最佳实践",
		difficulty: 6,
		category: "线下管理",
		description: "传统管理优化",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
		],
	},
	{
		id: "6-2-3",
		text: "构建团队协作式客户管理的效果评估体系",
		difficulty: 6,
		category: "团队协作评估",
		description: "传统团队管理分析",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
		],
	},
	{
		id: "6-2-4",
		text: "分析客户-联系人-业务员团队的最优配置策略",
		difficulty: 6,
		category: "配置策略",
		description: "传统CRM配置优化",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
		],
	},
	{
		id: "6-2-5",
		text: "找出传统跟进模式下的高价值客户培养路径",
		difficulty: 6,
		category: "培养路径",
		description: "传统模式客户培养",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
		],
	},

	// 缺少商机的分析 (关系维护导向)
	{
		id: "6-3-1",
		text: "分析客户自然发展状态下的业务表现",
		difficulty: 6,
		category: "自然发展",
		description: "无主动跟进分析",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-3-2",
		text: "找出无需频繁跟进的优质客户特征",
		difficulty: 6,
		category: "优质客户",
		description: "自驱动客户识别",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-3-3",
		text: "构建基于关系维护的客户满意度模型",
		difficulty: 6,
		category: "关系维护模型",
		description: "非商机导向客户分析",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"whatsappMessages",
		],
	},
	{
		id: "6-3-4",
		text: "分析多渠道客户互动对关系质量的影响",
		difficulty: 6,
		category: "关系质量分析",
		description: "互动关系质量建模",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"whatsappMessages",
		],
	},
	{
		id: "6-3-5",
		text: "找出最能建立长期合作关系的客户服务策略",
		difficulty: 6,
		category: "长期合作策略",
		description: "关系导向服务优化",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"whatsappMessages",
		],
	},

	// 缺少跟进的分析 (自然商机发展)
	{
		id: "6-4-1",
		text: "分析客户关系维护的基础工作效果",
		difficulty: 6,
		category: "关系维护",
		description: "基础工作价值",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"whatsappMessages",
		],
	},
	{
		id: "6-4-2",
		text: "找出客户满意度最高的服务组合",
		difficulty: 6,
		category: "服务组合",
		description: "非商机导向服务",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"whatsappMessages",
		],
	},
	{
		id: "6-4-3",
		text: "构建自然商机转化的客户特征模型",
		difficulty: 6,
		category: "自然转化模型",
		description: "无主动跟进商机分析",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-4-4",
		text: "分析WhatsApp自然沟通对商机产生的影响",
		difficulty: 6,
		category: "自然沟通影响",
		description: "自发沟通商机分析",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-4-5",
		text: "找出最能自发产生商机的客户管理模式",
		difficulty: 6,
		category: "自发商机模式",
		description: "自然商机产生机制",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 缺少团队关系的分析 (个人业务员导向)
	{
		id: "6-5-1",
		text: "分析公司级别客户管理的整体效果",
		difficulty: 6,
		category: "公司级管理",
		description: "企业客户分析",
		tables: [
			"companies",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-5-2",
		text: "找出企业客户开发的最佳路径",
		difficulty: 6,
		category: "开发路径",
		description: "B2B开发策略",
		tables: [
			"companies",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-5-3",
		text: "构建个人业务员多渠道客户管理效能模型",
		difficulty: 6,
		category: "个人效能模型",
		description: "单兵作战效果分析",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-5-4",
		text: "分析业务员独立管理客户的成功模式",
		difficulty: 6,
		category: "独立管理模式",
		description: "个人客户管理优化",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-5-5",
		text: "找出最适合个人业务员的客户类型和管理策略",
		difficulty: 6,
		category: "个人适配策略",
		description: "业务员客户匹配优化",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 缺少联系人的分析 (公司级客户分析)
	{
		id: "6-6-1",
		text: "分析客户自然属性对业务的影响",
		difficulty: 6,
		category: "客户属性",
		description: "内在价值分析",
		tables: [
			"companies",
			"contacts",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-6-2",
		text: "找出客户内在价值的评估模型",
		difficulty: 6,
		category: "价值评估",
		description: "客户价值建模",
		tables: [
			"companies",
			"contacts",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-6-3",
		text: "构建企业级客户的综合价值评估体系",
		difficulty: 6,
		category: "企业价值体系",
		description: "公司维度价值分析",
		tables: [
			"companies",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-6-4",
		text: "分析公司整体特征对业务发展的影响",
		difficulty: 6,
		category: "公司特征影响",
		description: "企业特征业务关联",
		tables: [
			"companies",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-6-5",
		text: "找出最适合企业级销售的客户管理模式",
		difficulty: 6,
		category: "企业销售模式",
		description: "B2B销售模式优化",
		tables: [
			"companies",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 缺少业务员的分析 (系统自动化分析)
	{
		id: "6-7-1",
		text: "构建客户自主行为与业务结果的关联模型",
		difficulty: 6,
		category: "自主行为模型",
		description: "客户自驱动行为分析",
		tables: [
			"companies",
			"contacts",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-7-2",
		text: "分析客户网络效应对商机产生的影响",
		difficulty: 6,
		category: "网络效应分析",
		description: "客户关系网络商机",
		tables: [
			"companies",
			"contacts",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-7-3",
		text: "找出最具自传播效应的客户群体特征",
		difficulty: 6,
		category: "自传播效应",
		description: "客户传播价值分析",
		tables: [
			"companies",
			"contacts",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 高级综合分析场景
	{
		id: "6-8-1",
		text: "构建客户细分的多维度决策树模型",
		difficulty: 6,
		category: "客户细分模型",
		description: "多维度细分决策",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-8-2",
		text: "分析客户行为模式对业务预测的价值",
		difficulty: 6,
		category: "行为预测价值",
		description: "行为模式预测建模",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-8-3",
		text: "找出影响客户决策周期的关键因素组合",
		difficulty: 6,
		category: "决策周期因素",
		description: "决策影响因素分析",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
		],
	},
	{
		id: "6-8-4",
		text: "构建客户满意度的多维度测量体系",
		difficulty: 6,
		category: "满意度测量",
		description: "客户满意度建模",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 风险与机会分析
	{
		id: "6-9-1",
		text: "分析客户流失风险的早期预警指标",
		difficulty: 6,
		category: "流失预警",
		description: "客户流失风险建模",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"whatsappMessages",
		],
	},
	{
		id: "6-9-2",
		text: "构建市场机会识别的智能分析框架",
		difficulty: 6,
		category: "机会识别",
		description: "市场机会分析模型",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-9-3",
		text: "找出客户价值提升的最佳干预时机",
		difficulty: 6,
		category: "价值提升时机",
		description: "客户价值干预优化",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 运营效率优化
	{
		id: "6-10-1",
		text: "构建销售运营效率的综合评估模型",
		difficulty: 6,
		category: "运营效率",
		description: "销售运营效率建模",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
		],
	},
	{
		id: "6-10-2",
		text: "分析资源配置对客户管理效果的影响",
		difficulty: 6,
		category: "资源配置效果",
		description: "资源配置优化分析",
		tables: [
			"companies",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "6-10-3",
		text: "找出提升团队协作效率的关键要素",
		difficulty: 6,
		category: "协作效率要素",
		description: "团队协作优化分析",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
		],
	},
];
