import type { QueryTask } from "../constants";

export const lv7: QueryTask[] = [
	// 企业级数据大屏与BI
	{
		id: "7-1-1",
		text: "构建企业客户管理的完整数据大屏",
		difficulty: 7,
		category: "数据大屏",
		description: "全系统数据可视化",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-1-2",
		text: "分析CRM系统ROI的综合计算模型",
		difficulty: 7,
		category: "ROI模型",
		description: "投资回报率建模",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-1-3",
		text: "找出影响客户lifetime value的所有因素",
		difficulty: 7,
		category: "LTV分析",
		description: "客户生命周期价值",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-1-4",
		text: "统计CRM各个模块对业绩的贡献度",
		difficulty: 7,
		category: "模块贡献",
		description: "功能模块价值评估",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-1-5",
		text: "构建CRM系统完整的健康度评估指标体系",
		difficulty: 7,
		category: "系统健康度",
		description: "CRM健康度全景评估",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-1-6",
		text: "分析业务数据质量对决策准确性的影响",
		difficulty: 7,
		category: "数据质量影响",
		description: "数据质量决策关联",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},

	// AI预测与智能分析
	{
		id: "7-2-1",
		text: "基于全量数据预测客户成交概率",
		difficulty: 7,
		category: "成交预测",
		description: "AI预测模型数据",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-2-2",
		text: "构建客户流失风险预警体系",
		difficulty: 7,
		category: "流失预警",
		description: "风险识别系统",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-2-3",
		text: "建立客户行为模式的智能识别算法",
		difficulty: 7,
		category: "行为识别",
		description: "客户行为模式AI分析",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-2-4",
		text: "构建下一个最佳行动的智能推荐引擎",
		difficulty: 7,
		category: "智能推荐",
		description: "下一步行动AI推荐",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-2-5",
		text: "分析客户情感变化轨迹与业务机会的关联",
		difficulty: 7,
		category: "情感轨迹分析",
		description: "客户情感业务机会建模",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 销售团队360度绩效体系
	{
		id: "7-3-1",
		text: "构建销售人员的360度绩效评价体系",
		difficulty: 7,
		category: "绩效体系",
		description: "全维度绩效评估",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-3-2",
		text: "分析团队协作对整体业绩的影响",
		difficulty: 7,
		category: "团队协作",
		description: "协作效果量化",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-3-3",
		text: "建立销售人员能力模型与培训需求分析",
		difficulty: 7,
		category: "能力模型",
		description: "销售能力建模培训",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-3-4",
		text: "构建销售团队的动态激励优化模型",
		difficulty: 7,
		category: "激励模型",
		description: "团队激励动态优化",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-3-5",
		text: "分析个人风格与团队配合的最优组合模式",
		difficulty: 7,
		category: "团队配合优化",
		description: "个人团队风格匹配",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 客户智能细分与个性化
	{
		id: "7-4-1",
		text: "基于全维度数据进行客户精准细分",
		difficulty: 7,
		category: "客户细分",
		description: "多维度客户画像",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-4-2",
		text: "分析不同客户群体的最优服务策略",
		difficulty: 7,
		category: "服务策略",
		description: "个性化服务模型",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-4-3",
		text: "构建客户价值分层的动态管理体系",
		difficulty: 7,
		category: "价值分层管理",
		description: "客户价值动态分层",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-4-4",
		text: "建立客户需求预测与产品匹配推荐系统",
		difficulty: 7,
		category: "需求预测匹配",
		description: "客户需求产品匹配AI",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-4-5",
		text: "分析客户生命周期各阶段的个性化触点策略",
		difficulty: 7,
		category: "生命周期触点",
		description: "客户生命周期个性化",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 业务流程智能优化
	{
		id: "7-5-1",
		text: "分析从线索到成交的完整流程效率",
		difficulty: 7,
		category: "流程效率",
		description: "端到端流程分析",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-5-2",
		text: "找出业务流程中的瓶颈和优化点",
		difficulty: 7,
		category: "流程优化",
		description: "瓶颈识别与优化",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-5-3",
		text: "构建销售流程自动化的智能决策树",
		difficulty: 7,
		category: "流程自动化",
		description: "销售流程智能自动化",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-5-4",
		text: "分析客户接触点的全触点体验优化方案",
		difficulty: 7,
		category: "全触点体验",
		description: "客户接触点体验优化",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 市场趋势与商业洞察
	{
		id: "7-6-1",
		text: "基于客户数据分析市场趋势和机会",
		difficulty: 7,
		category: "市场分析",
		description: "趋势预测与机会识别",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-6-2",
		text: "构建客户需求变化的趋势预测",
		difficulty: 7,
		category: "需求预测",
		description: "需求趋势建模",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-6-3",
		text: "建立竞争对手分析与市场定位策略模型",
		difficulty: 7,
		category: "竞争分析",
		description: "竞争对手市场定位",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-6-4",
		text: "分析行业发展周期对客户行为的影响",
		difficulty: 7,
		category: "行业周期影响",
		description: "行业周期客户行为",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 风险管理与合规
	{
		id: "7-7-1",
		text: "构建客户信用风险评估体系",
		difficulty: 7,
		category: "风险评估",
		description: "信用风险建模",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-7-2",
		text: "分析异常交易和可疑行为模式",
		difficulty: 7,
		category: "异常检测",
		description: "行为模式识别",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-7-3",
		text: "建立客户数据安全与隐私保护监控体系",
		difficulty: 7,
		category: "数据安全",
		description: "客户数据安全监控",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-7-4",
		text: "构建合规风险的实时预警与处置机制",
		difficulty: 7,
		category: "合规风险",
		description: "合规风险预警处置",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 智能决策支持系统
	{
		id: "7-8-1",
		text: "构建基于数据驱动的运营决策模型",
		difficulty: 7,
		category: "决策模型",
		description: "智能决策支持",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-8-2",
		text: "分析资源投入与产出的最优配比",
		difficulty: 7,
		category: "资源配置",
		description: "投入产出优化",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-8-3",
		text: "建立战略目标分解与执行监控体系",
		difficulty: 7,
		category: "战略执行",
		description: "战略目标执行监控",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-8-4",
		text: "构建多维度KPI的动态平衡优化模型",
		difficulty: 7,
		category: "KPI优化",
		description: "多维度KPI动态平衡",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 数字化转型与创新
	{
		id: "7-9-1",
		text: "分析数字化程度对客户满意度的影响",
		difficulty: 7,
		category: "数字化影响",
		description: "数字化满意度关联",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-9-2",
		text: "构建客户数字化成熟度评估与提升路径",
		difficulty: 7,
		category: "数字化成熟度",
		description: "客户数字化评估提升",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-9-3",
		text: "建立新技术对销售效率提升的量化模型",
		difficulty: 7,
		category: "技术效率提升",
		description: "新技术销售效率建模",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-9-4",
		text: "分析创新服务模式对客户价值创造的贡献",
		difficulty: 7,
		category: "创新价值贡献",
		description: "创新服务价值创造",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 生态系统与网络效应
	{
		id: "7-10-1",
		text: "构建客户生态网络的价值流动分析模型",
		difficulty: 7,
		category: "生态价值流动",
		description: "客户生态网络价值",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-10-2",
		text: "分析合作伙伴网络对客户获取的影响",
		difficulty: 7,
		category: "伙伴网络影响",
		description: "合作伙伴客户获取",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-10-3",
		text: "建立客户推荐与口碑传播的量化评估体系",
		difficulty: 7,
		category: "口碑传播",
		description: "客户推荐口碑量化",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 可持续发展与社会责任
	{
		id: "7-11-1",
		text: "分析ESG因素对客户关系的长期影响",
		difficulty: 7,
		category: "ESG影响",
		description: "ESG客户关系影响",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-11-2",
		text: "构建可持续商业模式的客户价值创造体系",
		difficulty: 7,
		category: "可持续价值",
		description: "可持续商业价值创造",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 全球化与本地化
	{
		id: "7-12-1",
		text: "分析跨文化客户管理的最优策略模型",
		difficulty: 7,
		category: "跨文化管理",
		description: "跨文化客户策略",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-12-2",
		text: "构建全球化与本地化平衡的客户服务体系",
		difficulty: 7,
		category: "全球本地化",
		description: "全球本地化服务平衡",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},

	// 未来趋势与创新实验
	{
		id: "7-13-1",
		text: "建立面向未来的客户关系管理创新实验室",
		difficulty: 7,
		category: "创新实验室",
		description: "未来CRM创新实验",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
	{
		id: "7-13-2",
		text: "分析新兴技术对客户行为变革的预测模型",
		difficulty: 7,
		category: "技术变革预测",
		description: "新技术客户行为预测",
		tables: [
			"companies",
			"contacts",
			"salesUsers",
			"companyUserRelations",
			"followUps",
			"opportunities",
			"whatsappMessages",
		],
	},
];
